### ISSUE TITLE
如何自建模板，尝试自建demo目录发现demo无法被选中

### ISSUE THREAD

**Issue by xfeng-github** [gejun123456/EasyCodeMybatisCodeHelperTemplates#12]
![image](https://github.com/user-attachments/assets/7c5828a7-9400-42b5-affd-2feb7767a235)

**Comment by gejun123456** [comment]
group.json 文件看一下

**Comment by xfeng-github** [comment]
> group.json 文件看一下

group.json
`[
  {
    "groupName": "MybatisWithControllerNoServiceInterface",
    "templateName": "MybatisCodeHelperMigrateWithControllerNoServiceInterfaceCopy",
    "globalConfigName": "MybatisCodeHelperPro",
    "columnConfigName": "Default.json",
    "typeMapperName": "Default.json",
    "tableNameRegex": ".*",
    "schemaNameRegex": ".*"
  },
  {
    "groupName": "MybatisCodeHelperMigrate",
    "templateName": "MybatisCodeHelperMigrate",
    "globalConfigName": "MybatisCodeHelperPro",
    "columnConfigName": "Default.json",
    "typeMapperName": "Default.json",
    "tableNameRegex": ".*",
    "schemaNameRegex": ".*"
  },
  {
    "groupName": "MybatisCodeHelperMigrateNoServiceNoController",
    "templateName": "MybatisCodeHelperMigrateNoServiceInterfaceNoController",
    "globalConfigName": "MybatisCodeHelperPro",
    "columnConfigName": "Default.json",
    "typeMapperName": "Default.json",
    "tableNameRegex": ".*",
    "schemaNameRegex": ".*"
  },
  {
    "groupName": "MybatisPlus",
    "templateName": "MybatisPlusMigrate",
    "globalConfigName": "MybatisCodeHelperPro",
    "columnConfigName": "Default.json",
    "typeMapperName": "Default.json",
    "tableNameRegex": ".*",
    "schemaNameRegex": ".*"
  },
  {
    "groupName": "jpa",
    "templateName": "jpa",
    "globalConfigName": "jpa",
    "columnConfigName": "Default.json",
    "typeMapperName": "Default.json",
    "tableNameRegex": ".*",
    "schemaNameRegex": ".*"
  }
]
`

这上面看确实没有我添加的demo目录，需要手动在这边维护一条数据吗

**Comment by xfeng-github** [comment]
我是通过在scratches工作目录通过新建文件夹的方式创建demo目录，这种方式有什么问题吗

**Comment by gejun123456** [comment]
对的，需要把你的demo添加到group.json 中 templateName 用你的那个

**Comment by xfeng-github** [comment]
好的感谢
