### ISSUE TITLE
更新版本后本地模板丢失

### ISSUE THREAD

**Issue by Jimmer1993** [gejun123456/EasyCodeMybatisCodeHelperTemplates#2]
原有版本没有generate from scratch file的选项。

**Comment by gejun123456** [comment]
可以先降级一下插件，把模版导出为json 再到新版本里面导入模版
https://plugins.jetbrains.com/plugin/13847-easycode-mybatiscodehelper/versions
这里可以下载到老插件版本

**Comment by gejun123456** [comment]
用1.2.6版本 1.2.7版本后为了避免与easyCode插件冲突修改了配置文件地址

**Comment by gejun123456** [comment]
建议使用genearate from scratch 那个功能，模版保存在本地，可以用git来版本管理，不会丢失模版

**Comment by Jimmer1993** [comment]
> 搞定了吗

搞定了 谢谢
