### ISSUE TITLE
更新版本后本地模板丢失

### ISSUE THREAD

**Issue by Jimmer1993** [gejun123456/EasyCodeMybatisCodeHelperTemplates#3]
原有版本没有generate from scratch file的选项。
更新后多了generate from scratch file,
使用generate code（old）时原有的自定义模板都没了

**Comment by gejun123456** [comment]
可以先降级一下插件，把模版导出为json 再到新版本里面导入模版 
https://plugins.jetbrains.com/plugin/13847-easycode-mybatiscodehelper/versions
这里可以下载到老插件版本
