### ISSUE TITLE
最新版本生成代码不了,没有错误提示

### ISSUE THREAD

**Issue by zhouyufei8** [gejun123456/EasyCodeMybatisCodeHelperTemplates#5]

**Comment by zhouyufei8** [comment]
![image](https://github.com/gejun123456/EasyCodeMybatisCodeHelperTemplates/assets/25834570/2f805041-6d47-4ff2-9462-c04bbbb6a8ef)
 点击ok ,没有反应, 插件版本1.3.1
idea版本, 
![image](https://github.com/gejun123456/EasyCodeMybatisCodeHelperTemplates/assets/25834570/33eaae60-1cf6-4c5d-9532-db516cb1dc53)

**Comment by zhouyufei8** [comment]
模版选择mybatisPlus 可以, 选择MybatisCodeHelperMigrate 不行

**Comment by gejun123456** [comment]
搞定了么

**Comment by zhouyufei8** [comment]
> 搞定了么

搞定了,谢谢
