### ISSUE TITLE
如果用新的生成方式，无法读取到package变量

### ISSUE THREAD

**Issue by leo9082** [gejun123456/EasyCodeMybatisCodeHelperTemplates#7]
如题，${package}没有值

**Comment by gejun123456** [comment]
发下模版来看一下 或者联系我看看

**Comment by leo9082** [comment]
如图，我看了旧版本的模板，是有package这个变量的。但在新版本中，这个变量无法读取到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月12日(星期六) 下午5:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gejun123456/EasyCodeMybatisCodeHelperTemplates] 如果用新的生成方式，无法读取到package变量 (Issue #7)





 
发下模版来看一下 或者联系我看看

**Comment by leo9082** [comment]
![](https://i.imgur.com/bVzmfAp.png)
![](https://i.imgur.com/7JRoOW1.png)

如图，package这个变量无法读取到值

**Comment by gejun123456** [comment]
![image](https://github.com/gejun123456/EasyCodeMybatisCodeHelperTemplates/assets/6340473/d80b5b5c-2396-4809-acb9-dfe9965956b1)
你是在ui那里配置了包名吧，要用这个， 或者你把包名给写死

**Comment by leo9082** [comment]
好的，最好能有个说明，有哪些可读取的变量，方便改模板的时候用
